things_we_did = ['we invented the word "batoon"',
                 'we wrote the song Plumbers on the Hunt',
                 'we went to the cat cafe',
                 'we turned Korben into a feather addict',
                 "we didn't get in to Rocky Mountain National Park",
                 'we walked in Cheeseman park',
                 'we broke the car',
                 'we got the car fixed',
                 'we discovered our favorite sausage',
                 'we worried about toilet paper',
                 'we found some fancy masks on Etsy',
                 'we walked in Bear Creek Lake Park',
                 'we saw a snake',
                 'you ran away and left me to get eaten by a snake',
                 'we saw a moose taking a bath',
                 'we endured some noisy people and worried that their kid would get eaten by the moose',
                 'we applied for jobs',
                 'we learned how to use zoom',
                 'we got you a fancy pink computer',
                 'Korben jumped on your fancy new pink computer and might have broken it',
                 'Leeloo jumped on my fancy keyboard and might have broken that',
                 'we got heatstroke',
                 'you turned into an eggplant',
                 'you turned into a red lobster',
                 'you turned into a tomato head',
                 'we protested in the streets',
                 'we updated our LinkedIns a lot',
                 'you stole my slippees',
                 'we went inside one of the fancy houses in the rich people neighborhood',
                 'I got stung by a wasp and thought I was going to die',
                 'we did get in to Rocky Mountain National Park',
                 'we found out I was going back to school while we were on top of a mountain',
                 'we looked at a tiny little basement flat with pipes coming out of the walls',
                 'you got the cats a tube',
                 'the cats fell in love with the tube',
                 'Korben scratched us both',
                 'some jerks in a yellow truck yelled at us on the road',
                 'we started fasting every day',
                 'we tried a bunch of new breakfast bars',
                 'I stole your cookie paste',
                 'I cleaned the bathroom more than I ever did before ;)',
                 'our neighbor had a manic episode and stole our bathmat',
                 'we watched The Umbrella Academy',
                 'we watched Peaky Blinders',
                 'we re-watched New Girl',
                 'we watched Unforgotten',
                 'we got Plantgelina Joleaf',
                 'we killed Plantgelina Joleaf',
                 'we helped a guy with his tent',
                 'there were a million moths in our apartment',

                 ]

birthday_message = 'Dear Aglaia,\n\n\tHappy 34th Birthday! I made you this app so you can remember all of the things ' \
                   'we did this crazy year. To use it, just click one of the buttons! The "All The Things" button ' \
                   'shows you a list of everything we did together this year, and the "Random Thing" button will show you ' \
                   'a random thing. If you want to copy and paste one of them, just click the one you want to copy ' \
                   'and use cmd + c to copy it.\n\n\tI wanted to give you this so we never forget just how much stuff ' \
                   'we did together this year. It was fun, stressful, satisfying, demanding, happy, and sad, ' \
                   'but I wouldn\'t trade these memories for the world.' \
                   '\n\nWith all of my love and then some more,\nBill'
